### ISSUE TITLE
compile error vs2013

### ISSUE THREAD

**Issue by sailfish009** [emilk/loguru#19] opened 2016-09-09 11:05 UTC
Hi, how to work around this error? 

http://stackoverflow.com/questions/24573963/move-constructor-invalid-type-for-defaulted-constructor-vs-2013

loguru.h(452): error C2610: 'loguru::LogScopeRAII::LogScopeRAII(loguru::LogScopeRAII &&)' : is not a special member function which can be defaulted

```
    // Helper class for LOG_SCOPE_F
    class LogScopeRAII
    {
    public:
        LogScopeRAII() : _file(nullptr) {} // No logging
        LogScopeRAII(Verbosity verbosity, const char* file, unsigned line, LOGURU_FORMAT_STRING_TYPE format, ...) LOGURU_PRINTF_LIKE(5, 6);
        ~LogScopeRAII();

        LogScopeRAII(LogScopeRAII&& other) = default;                       //  here
```

**Comment by sailfish009** [comment] 2016-09-10 02:06
Below code will be enough for me?
#if _MSC_VER >1800
LogScopeRAII(LogScopeRAII&& other) = default;
#else 
LogScopeRAII(LogScopeRAII&& other);
#endif

**Comment by emilk** [comment] 2016-09-12 08:42
That doesn't seem like a solid fix. Doesn't the linker start complaining about missing definition of `LogScopeRAII(LogScopeRAII&& other)`? 

Make sure the function is used by adding this code somewhere:

`LOG_SCOPE_F(INFO, "Blah blah");`

**Comment by sailfish009** [comment] 2016-09-13 08:37
no complaining, it just works.
Thanks for the info.

currently i am only using follow macro.
```
#define LOG_ERROR(...)					LOG_F(ERROR, __VA_ARGS__)
#define LOG_WARNING(...)  				LOG_F(WARNING, __VA_ARGS__)
#define LOG_INFO(...)					LOG_F(INFO, __VA_ARGS__)
#define LOG_FATAL(...)					LOG_F(FATAL, __VA_ARGS__)
```

should i have to replace the code with this?
`#define LOG_INFO(...)					LOG_SCOPE_F(INFO, __VA_ARGS__)`

**Comment by zao** [comment] 2016-09-13 09:21
I wonder @sailfish009, have you locally patched all the other things that VS2013 gets stuck on?
When trying to reproduce this, I ran into at least:

* no `snprintf`,
* no `thread_local`,
* no `noexcept(false)`,
* `'\u0013'` not being a character.

@emilk The missing definition will probably work for them as long as they don't try to move-construct the object. If moving is intended to work, an actual definition is needed.

**Comment by emilk** [comment] 2016-09-29 20:23
`#define LOG_INFO(...) LOG_F(INFO, __VA_ARGS__)` is probably what you want - `LOG_SCOPE_F` does something else (try it!).

You patch for `thread_local` will break `ERROR_CONTEXT` in threaded environments, which I don't think is very nice. I honestly would prefer no vs2013 support to broken support.

As for snprintf: the current code is courtesy of John Cannon in commit 75772005 which was for 2015 support. Can you please try something along the following lines and see if that works:

```
@@ -1412,7 +1412,11 @@ namespace loguru
    static Text vtextprintf(const char* format, va_list vlist)
    {
 #ifdef _MSC_VER
+   #if _MSC_VER <= 1800
+       int bytes_needed = vsnprintf(nullptr, 0, format, vlist);
+   #else
        int bytes_needed = _vscprintf(format, vlist);
+   #endif
        CHECK_F(bytes_needed >= 0, "Bad string format: '%s'", format);
        char* buff = (char*)malloc(bytes_needed+1);
        vsnprintf(buff, bytes_needed+1, format, vlist);
```

**Comment by zao** [comment] 2016-09-30 10:58
VC++ has `__declspec(thread)` for its native flavor of TLS. There are probably amusing differences between it and proper `thread_local`.

Note the caveats in the [MSDN documentation](https://msdn.microsoft.com/en-us/library/9w1sdazb(v=vs.120).aspx).

**Comment by sailfish009** [comment] 2016-10-04 02:23
thanks for the information.

for thread_local, just patched it.
https://github.com/sailfish009/loguru/commit/4d5ecf225a3711a566189c0b22bcd4e9088c0992

and for snprintf, i have no reason to implement another patch.
my patch from google search works fine.
give me a reason then i will test and patch it.

Thank you.

**Comment by emilk** [comment] 2017-02-05 11:22
I will close this until somebody has more trouble with vs2013 again.

**Closed by emilk** 2017-02-05 11:22 UTC
